2022-07-08 17:55:36,805 ERROR: Exception on /user/g [GET] [in /mnt/e/microblog/venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/mnt/e/microblog/app/routes.py", line 82, in user
    return render_template('user.html', user=user, posts=posts, form=form)
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/mnt/e/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/mnt/e/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/mnt/e/microblog/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/mnt/e/microblog/app/templates/user.html", line 34, in block 'content'
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2022-07-08 17:58:03,769 INFO: Microblog startup [in /mnt/e/microblog/app/__init__.py:44]
